### ISSUE TITLE
Convert to Docker action and add Gitlab support

### ISSUE THREAD

**Issue by chazwatkins** [mitchspano/sfdx-scan-pull-request#22]
Hey @mitchspano -  This is a cool ci action.  Would you be open to converting this to a Docker action and adding support for GitLab?  If so, I'm happy to do it.

**Comment by mitchspano** [comment]
Hey Chaz,

Thanks for your interest and support! There are a couple of particular things for this Action which make it tightly coupled to a GitHub pull request context:

1. Parsing the Git diff from the pull request
2. Writing the comments with the findings using the GitHub REST API.

I'm curious to hear your thoughts about how writing this as a container action will support the additional context of GitLab.

**Comment by chazwatkins** [comment]
Writing it as a container will not make the action support GitLab alone.  GitLab doesn't support javascript "actions" but does support docker "actions".

I believe bitbucket pipelines can utilize docker images as well.

The following would need to be done to make it work with multiple git providers:

- Convert to docker
- Make diff parsing logic and comment creation generic with plugins for different git providers

If you feel this is outside what you want this repo's scope to be.  That's completely understandable.  I can always use this repo as inspiration and build one for GitLab.
