### ISSUE TITLE
Ability to run on push or pull request?

### ISSUE THREAD

**Issue by initdotd** [mitchspano/sfdx-scan-pull-request#32]
I've found having the scanner run on a push to a remote feature branch to be helpful even before opening a PR.  This provides really great feedback to the contributor prior to engaging code reviews and CI builds during the PR process.  My projects would really benefit from such a flag/feature.

1. Provide the ability to run on push 
2. Avoid comment creation on push
3. Still fail sanity check on push to remote
4. No change to existing PR functionality

**Comment by mitchspano** [comment]
This is possible when using the `target` parameter:

https://github.com/mitchspano/sfdx-scan-pull-request?tab=readme-ov-file#target
