### ISSUE TITLE
Feature Request: Create Review comments for Pull Request.

### ISSUE THREAD

**Issue by codefriar** [mitchspano/sfdx-scan-pull-request#45]
The pull request timeline comments are lovely. I think I'd rather see these comments as review comments, however. The Github api looks to support it. (https://docs.github.com/en/rest/pulls/comments?apiVersion=2022-11-28#create-a-review-comment-for-a-pull-request) but I'm not sure of the LOE needed to implement. It looks like you already have the file, position, etc are already available to you in the context where the timeline comment is being created. this also looks to require a 'side' parameter, but I'm guessing that can be assumed to be 'right' most of the time.

**Comment by mitchspano** [comment]
The comments which are produced as part of the scan _are_ review comments.
Check out the [endpoint](https://github.com/mitchspano/sfdx-scan-pull-request/blob/main/src/reporter/comments-reporter.ts#L45) we are POSTing to when creating the comments:

```js
const endpoint = `${method} /repos/${owner}/${repo}/${
      prNumber ? `pulls/${prNumber}` : `commits/${context.sha}`
    }/comments`;
```

It's the same endpoint as mentioned in the documentation shared above.

The other kind of comment is called an "Issue Comment" and those can show up on the timeline when a PR number is referenced in a comment on an issue - something like:

```
The fix for this is included in PR #12345 and should be ready before the end of this week.
```

Those comments will show up on the PR's timeline, but are not explicitly review comments.
