### ISSUE TITLE
Error in Run SFDX Scanner - Report findings as comments

### ISSUE THREAD

**Issue by bbarlow-knauf** [mitchspano/sfdx-scan-pull-request#46]
Hi I get an error when running this action against my repo.

Here is my YAML file
`name: Static Analysis
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - '**.cls'
      - '**.trigger'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install SFDX CLI and Scanner
        run: |
          npm install sfdx-cli -g
          sfdx plugins:install @salesforce/sfdx-scanner

      - name: Run SFDX Scanner - Report findings as comments
        uses: mitchspano/sfdx-scan-pull-request@v0.1.8
        with:
          pmdconfig: .github/workflows/pmd-ruleset.xml
          # severity-threshold: 4
          # strictly-enforced-rules: '[{ "engine": "pmd", "category": "Performance", "rule": "AvoidDebugStatements" }]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
`
Here is the log from the failed action
[SFDX Source Scanner Action Error.txt](https://github.com/mitchspano/sfdx-scan-pull-request/files/11204890/SFDX.Source.Scanner.Action.Error.txt)

Thanks

**Comment by mitchspano** [comment]
Hey there - thanks for checking out the action! Version 1.0.8 has some issues 😕 I would recommend upgrading to 1.0.9 and let me know how that works for you.

**Comment by mitchspano** [comment]
@bbarlow-knauf I have added some enhanced logging when calling the REST API. Can you please try with 0.1.10 and let me know what you see?

**Comment by mitchspano** [comment]
@bbarlow-knauf - Are you still experiencing issues with this scan?
Please upgrade to v0.1.12 and let me know if the scan is still failing.

Thanks!

**Comment by bbarlow-knauf** [comment]
Hi @mitchspano I updated to use the latest version. Still getting errors. Attached log Thanks.

[sfdx scanner result.txt](https://github.com/mitchspano/sfdx-scan-pull-request/files/11627134/sfdx.scanner.result.txt)

**Comment by mitchspano** [comment]
The error message is included in the output of the log:

```
The PMD config file ruleset.xml couldn't be found.
```

It looks like the path to the ruleset file is incorrect, or the ruleset file does not exist.
