### ISSUE TITLE
getting httperror(403) while invoking from an githubaction

### ISSUE THREAD

**Issue by Balakrishnaraorj** [mitchspano/sfdx-scan-pull-request#67]
Hi, I am trying to follow the steps in the Github readme for the SFdx-scan-pull-request.
I am getting httperror(403) and the scan is not happening.

![Screenshot 2023-11-29 at 10 21 38](https://github.com/mitchspano/sfdx-scan-pull-request/assets/24600043/4994ba4c-7fe6-47dc-b273-24868da474ff)

Could you please guide me where is the issue and how to resolve those

**Comment by Balakrishna-Rao** [comment]
Thank you. I gave permission in github runner. I gave write-all permission and it worked.
