### ISSUE TITLE
Configure the PMD version the Action uses?

### ISSUE THREAD

**Issue by rsoesemann** [mitchspano/sfdx-scan-pull-request#70]
@mitchspano, we are using your action in a project and I want to use it with the latest PMD 7 Release Candidate. Because only this RC contains the latest Salesforce Apex parser which understands `for user` DML.

All v6 crash on this and the Final v7 will contain the [new Apex parser contributed by your fellow Googlers](https://github.com/pmd/pmd/issues/3766). By the way...do you know anything about this effort?

**Comment by mitchspano** [comment]
Thanks for bringing this to my attention.

For all intents and purposed, this action really is a wrapper around the SFDX scanner plugin, which currently has no support for specifying a PMD version in their commands:

https://forcedotcom.github.io/sfdx-scanner/en/v3.x/scanner-commands/run/

So I don't think this is feasible
